# numpy practice session

In [2]:
#pip install numpy

In [3]:
#import this library in jupyter notebook
import numpy as np

# Creting an array using numpy

In [18]:
#!-D array
food = np.array(["Pakora", "Samosa", "Raita"])
food

array(['Pakora', 'Samosa', 'Raita'], dtype='<U6')

In [10]:
price = np.array([5,5,5])
price

array([5, 5, 5])

In [11]:
#Type
type(price)

numpy.ndarray

In [12]:
#Type
type(food)

numpy.ndarray

In [13]:
#length
len(price)

3

In [14]:
#length
len(food)

3

In [15]:
#Indexing
price[2]

5

In [16]:
#Indexing
price[0:]

array([5, 5, 5])

In [19]:
#Indexing
food[1]

'Samosa'

In [20]:
#zeros
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [21]:
#array of ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [22]:
#empty
np.empty(5)

array([1., 1., 1., 1., 1.])

In [23]:
#range
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
#to specify a range
np.arange(2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [25]:
#to specify a range with specific interval
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [28]:
#table
np.arange(5,55,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [34]:
#line space
np.linspace(0,100, num=9)

array([  0. ,  12.5,  25. ,  37.5,  50. ,  62.5,  75. ,  87.5, 100. ])

In [37]:
#specify your data type
np.ones(50, dtype=np.int64)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1], dtype=int64)

In [38]:
np.ones(50, dtype=np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## Array functions

In [40]:
a = np.array([10,12,15,10.0, 14,3,23.6])
a

array([10. , 12. , 15. , 10. , 14. ,  3. , 23.6])

In [41]:
a.sort()
a

array([ 3. , 10. , 10. , 12. , 14. , 15. , 23.6])

In [42]:
b=np.array([10,39,45.6,84.6, 4, 5])
b

array([10. , 39. , 45.6, 84.6,  4. ,  5. ])

In [45]:
c=np.concatenate((a,b))
c

array([ 3. , 10. , 10. , 12. , 14. , 15. , 23.6, 10. , 39. , 45.6, 84.6,
        4. ,  5. ])

## 2-D arrays

In [52]:
a=np.array([[1,2], [3,6]])
a

array([[1, 2],
       [3, 6]])

In [53]:
b=np.array([[6,7],[8,9]])
b

array([[6, 7],
       [8, 9]])

In [55]:
c=np.concatenate((a,b), axis=0)
c

array([[1, 2],
       [3, 6],
       [6, 7],
       [8, 9]])

In [56]:
c=np.concatenate((a,b), axis=1)
c

array([[1, 2, 6, 7],
       [3, 6, 8, 9]])

In [57]:
#To find the number of dimensions
a.ndim

2

In [64]:
b=np.array([[5,6,7],
            [8,9,10],
           [10,11,12]])
b

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [10, 11, 12]])

In [65]:
b.ndim

2

In [66]:
#to check size menas numnebr of elements
b.size

9

In [67]:
#shape
b.shape

(3, 3)

In [74]:
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [76]:
#reshape
a=a.reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [77]:
#reshape
np.reshape(a, newshape=(1,9), order= 'C')

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [79]:
#Convert 1D to 2D
a = np.array([1,2,3,4,5,6,7,8,9])
a


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
a.shape

(9,)

In [82]:
#row wise 2D conversion
b=a[np.newaxis, :]
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [83]:
b.shape

(1, 9)

In [85]:
#Colument wise 2D onversion
c=a[: , np.newaxis]
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [86]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
a[2:9]

array([3, 4, 5, 6, 7, 8, 9])

In [89]:
a*6

array([ 6, 12, 18, 24, 30, 36, 42, 48, 54])

In [90]:
a+6

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15])

In [92]:
a.sum()

45

In [93]:
a.mean()

5.0